### ISSUE TITLE
Provide upgrade stats as metrics and build a visualization in agent dashboards

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1340]
As a user I need to be able to monitor the rolling out of an upgrade to a cluster of Agent, to do so I need the following:

# Tasks
- [ ] Collect metrics (TBD with @nimarezainia )
  - Policy name
  - Agents upgraded already
  - Total agents in the policy
  - Number of failed upgrades
- [ ] Define the format structure (Look at ecs)
- [ ]  Send theses metrics into a data stream (define if we do it with log or send directly to a data stream)
- [ ] Create a dashboard to visualize that information.

The metric should include:

**Comment by jlind23** [comment]
@ph Could you tell me more about the `v8.3.0`label?

**Comment by ph** [comment]
This will contains our jobs for the rolling upgrade, going with Kibana as the schedule removes a lof of things required to be done in Fleet-Server. But we need to provide stats to monitor that upgrade.

**Comment by joshdover** [comment]
It might be helpful to think about these stats more generically, as agent status stats and then use that data to build the visualizations for upgrades. I don't think there's anything particular about the upgrades that need to be represented in the data, but an upgrade would change the general agent status.

> * Agents upgraded already
> * Total agents in the policy
> * Number of failed upgrades

All of these could be answered by a simple count of agents, broken down by version number and status.

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
