### ISSUE TITLE
[Meta] Fleet server should gracefully reject connections

### ISSUE THREAD

**Issue by mostlyjason** [elastic/fleet-server#153]
When incoming connections to Fleet server exceed the capacity for that server, we should gracefully reject those connections. This will allow the clients to be load balanced to other nodes, when available. 

Currently, Fleet server will consume all available RAM as the number of connections increases until it [triggers the OOM killer](https://github.com/elastic/fleet-server/issues/95#issuecomment-784225718). This will have a negative impact on clients and other processes. When a fleet server is killed, it will drop all connections, which would require many thousands of clients to reconnect, using a lot of CPU and prevent users from making updates or trigger response actions during that period. It will also negatively affect other processes running in the same container, such as APM server or Beats.

Requirements:
- We should reject incoming connections rather than crash or trigger the OOM killer
- We should account for ESS and self-managed clusters. We should not solely rely on a proxy to enforce limits. 
- The capacity should adjust based on the instance size in ESS/ECE and self-managed hosts
- We should provide some buffer for other processes in the same container, such as metricbeat which is essential to alert operators to scale capacity

Implementation phases:
- [ ] 1. Hard limit with manual adjustment in the integration policy https://github.com/elastic/fleet-server/issues/185
- [ ] 2. https://github.com/elastic/fleet-server/issues/466
- [ ] 3. Automatically accept more connections on larger instances https://github.com/elastic/fleet-server/issues/186
- [ ] 4. Autoscaling in ESS/ECE when limit is hit

Open questions:
1. What is the best approach to gracefully reject connections? Is it a hard limit, or can it intelligently reject connections if there is not enough free memory available?
    - Answer: Start with a hard limit and let the user adjust it. Make it more intelligent in a second phase.
2. Can we return an HTTP error code like 503 so the client knows why the request is rejected? It may be expensive to accept more TLS connections only to reject them. An alternative could be to give a tcp reset. This is not as clear when troubleshooting because tcp resets can also occur for other reasons like network connectivity.
    - Answer: Start with TCP reset because it doesn't require a TLS connection to be accepted, which would require more memory
3. If there is a limit, can we adjust it automatically so that the user does not need to manually adjust it, in ESS/ECE or self-managed hosts? Can it adjust so the cloud API doesn't need to alter the configuration? For example, the limit could be calculated based on the environment when the fleet server starts.
    - Answer: Lets target this for a second phase
4. Can we reject connections based on the amount of memory available? If other processes use too much memory, the fleet server might run out of memory before hitting a hard connection limit. This would lead us to use wider operating margins which are less cost efficient.
    - Answer from Steffen: The Agent would be in a better place to monitor and adapt limits dynamically if there is need. I don't think this is a short term goal.

Related issues:
- Fleet server should provide metrics on the number of rejected requests https://github.com/elastic/beats/issues/24415

**Comment by urso** [comment]
> Can we return an HTTP error code like 503 so the client knows why the request is rejected? It may be expensive to accept more TLS connections only to reject them. An alternative could be to give a tcp reset. This is not as clear when troubleshooting because tcp resets can also occur for other reasons like network connectivity.

In addition to returning 503 a [LimitListener](https://pkg.go.dev/golang.org/x/net/netutil#LimitListener) can be used to limit the total number of accepted connections. Additonal connection attempts will time out on the TCP level. No need for the TLS handshake.
The LimitListener is unfortunately static, but in essence it is just using a semaphore/counter to stop calling `Accept` once the limit is reached. A dynamic variant can be 'easily' implemented if there is need.

> Can we adjust the limit dynamically based on the amount of memory available? If other processes use too much memory, the fleet server might run out of memory before hitting the connection limit. This would lead us to use wider operating margins which are less cost efficient.

Although that would be nice, memory usage is somewhat unpredictable due to the other processes still running and competing for the same resources. The Agent would be in a better place to monitor and adapt limits dynamically if there is need. I don't think this is a short term goal.

**Comment by ph** [comment]
There is already an optional limiter added to the Fleet Server https://github.com/elastic/fleet-server/pull/122 by @scunningham.
 So we could have something initially and with testing we could probably define a safe high limit of the number of Agent a specific container can manage.

**Comment by mostlyjason** [comment]
Thanks for linking the PR! That looks like a fixed hard limit, hence why I added the open question about how this would work on ESS when the user drags the memory slider higher. I assume changing the slider would need to result in a changed limit, but I'm not sure on the mechanics of it.

> The Agent would be in a better place to monitor and adapt limits dynamically if there is need. I don't think this is a short term goal.

Ok thanks I can remove that as an open question

**Comment by ruflin** [comment]
We need to have an option to set these parameters dynamically in the future based on the memory / instance size. I think a first solution is to expose it in the integrations policy so users can adjust it.

**Comment by ph** [comment]
@ruflin @nchaulet is already modifying the integration to add hosts/port we can add `max_connection` with the same PR https://github.com/elastic/integrations/issues/803

**Comment by scunningham** [comment]
I have added additional controls to the server to allow both rate limiting per API call, and a cap on the number of parallel executions of that API.   This finer grained control allows us to tweak consumption rates on each API based on both memory and CPU impact to the system.  We can tune down rate of processing to lower the bursts.  Basically we trade performance for memory.

The control on the total number of accepted TCP connections remains in place as it allows us to limit a DOS attack which could take down the server by eating all the RAM or CPU with 10's of thousands of connections.

In the case of either of the API limits (max or rate limit), when the server cannot server it will immediately return an HTTP code 429.

**Comment by mostlyjason** [comment]
@ph @ruflin Should this one be in the 7.14 list? This will impact supportability at scale, particularly in the cloud free tier. I think it needs technical definition though.

**Comment by michel-laterman** [comment]
We have a connection limiter for the fleet-server and the ability to select defaults based off system memory.
