### ISSUE TITLE
[Meta] Fleet Server observability

### ISSUE THREAD

**Issue by mostlyjason** [elastic/fleet-server#173]
Observability for Fleet Servers is important because operators are expected to scale them manually. They are also expected to troubleshoot operational issues and fix them. This is true in various degrees from self-managed environments, to ECE/ECK and ESS. As a result, we should provide users visibility to issues and documentation on how to address common ones.

As a Fleet operator, I need:
- [ ] Logs, metric and status information to help me scale and troubleshoot issues https://github.com/elastic/beats/issues/24415
- [ ] Fleet Server integration dashboard https://github.com/elastic/integrations/issues/812
- [ ] Documentation for Fleet Server operators on to observe it, scale it, scaling limits, restrictions, etc.

Out of scope:
- A notification in the Fleet app when Fleet Server is not healthy so I understand why updates are not being applied elastic/kibana#95572

Related issues:
- Agent integration dashboard https://github.com/elastic/beats/issues/23948
- Enable system metrics on Elastic Cloud agent policy https://github.com/elastic/kibana/issues/96248

**Comment by jen-huang** [comment]
I merged the requirements here into the main meta issue for Fleet Server GA: #93. Closing.
