### ISSUE TITLE
Fleet Server API testing

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#2593]
Fleet server APIs listed below should be tested with integration tests. The purpose is to ensure that the behaviours remain the same as we should ensure backwards compatibility with Elastic Agent versions. All status code should be tested.
Api spec can be found [here](https://github.com/elastic/fleet-server/blob/e7d04c9d6eb40e04b679dc8f99cc5d7f00ec553a/model/openapi.yml#L1)

```[tasklist]
### Tasks
- [x] /api/status:
- [x] /api/fleet/agents/enroll:
- [x] /api/fleet/agents/{id}/checkin:
- [x] /api/fleet/agents/{id}/acks:
- [x] /api/fleet/artifacts/{id}/{sha2}:
- [x] /api/fleet/uploads:
- [x] /api/fleet/uploads/{id}/{chunkNum}:
- [x] /api/fleet/uploads/{id}
```

**Comment by michel-laterman** [comment]
We have a smoke test that makes calls to check the OK status on enroll, checkin, and ack: https://github.com/elastic/fleet-server/blob/main/internal/pkg/server/fleet_integration_test.go#L429

Other integration tests include checks that test various auth failures, and various request errors, and checkin timeout behaviour.

**Comment by amitkanfer** [comment]
this is before we added versioning.. correct?

**Comment by jlind23** [comment]
We do not have any versioning yet, as soon as we introduce it these tests needs to be extended the same way.

**Comment by michel-laterman** [comment]
200 responses for all endpoint are validated in the end to end tests: https://github.com/elastic/fleet-server/pull/2645
the existing integration tests validate some basic auth issues and request issues: https://github.com/elastic/fleet-server/blob/main/internal/pkg/server/fleet_integration_test.go#L544 and https://github.com/elastic/fleet-server/blob/main/internal/pkg/server/fleet_integration_test.go#L664.

If needed we could add additional validation to response bodies/headers as well as we currently don't check a lot.
We can also add coverage for:
* `X-Request-ID` header is populated by the server, or copied if the client specifies it
* `Accept` headers for gzip responses
* enrollment tags
* signed actions

**Comment by jlind23** [comment]
I believe this is good for now, we will continue on it as soon as the api versioning is introduced.
