### ISSUE TITLE
Fleet Server testing for versioned API

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#2594]
Fleet server APIs have to be versioned in order to ensure backwards compatibility with all already existing components calling it.
This issue is a placeholder that will be used as soon as the first versioned API is introduced.

```[tasklist]
### Tasks
- [ ] /api/status:
- [ ] /api/fleet/agents/enroll:
- [ ] /api/fleet/agents/{id}/checkin:
- [ ] /api/fleet/agents/{id}/acks:
- [ ] /api/fleet/artifacts/{id}/{sha2}:
- [ ] /api/fleet/uploads:
- [ ] /api/fleet/uploads/{id}/{chunkNum}:
- [ ] /api/fleet/uploads/{id}
```
