### ISSUE TITLE
[Meta] Fleet Server Phase 1

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#50]
This is a meta issue about all the tasks related to Phase 1 of the Fleet Server project.

* [x] Fleet Server is run by Elastic Agent https://github.com/elastic/beats/issues/22686 https://github.com/elastic/beats/pull/23736 (@blakerouse )
* [x] Elastic Agent with Fleet Server enrolls itself https://github.com/elastic/fleet-server/issues/55 (@blakerouse )
* [x] Elastic Agents can connect to Fleet Server and receive policies 
* [x] Bootstrapping of Elasticsearch indices works https://github.com/elastic/fleet-server/issues/51 (@scunningham  )
* [x] Usage of same data structure by Fleet in Kibana and Fleet Server (@nchaulet )
* [x] Define Data model (@blakerouse )
* [x] Actions like unenroll, upgrade etc. should work. Support the token. (@aleksmaus ) 
* [ ] User permission definition https://github.com/elastic/fleet-server/issues/60 (@scunningham  )
* [x] Fleet Server package https://github.com/elastic/integrations/issues/524 (@aleksmaus )
* [ ] Fleet Server onboarding flow https://github.com/elastic/kibana/issues/89396 (@mostlyjason )

CI

* [x] Fleet-Server is built as part of the release manager (@michalpristas )
* [ ] End to end tests exists for Elastic Agent startup, agent enrollment and receiving policy. https://github.com/elastic/e2e-testing/issues/438 (@blakerouse )
* [ ] Scale testing setup https://github.com/elastic/fleet-server/issues/25 (@aleksmaus )

**Comment by aleksmaus** [comment]
We probably need to figure how or what is going to clean up the old (older than 2 weeks) actions for the Phase 1, since we can't use the datastream with ILM policy for the actions.

We could do that with fleet, BUT:
1. This would require permissions to delete the actions documents by the fleet, which is not ideal.
2. The multiple instances of fleet would be cleaning the same data concurrently

Ideally it would be some scheduled period task at elasticsearch level. Not too familiar with this at the moment.

**Comment by mostlyjason** [comment]
I added 3 new items at the end of the top list. Let me know if there is a better place to track them. They could potentially be in phase 2, depending on when that is scheduled to be released.

**Comment by ruflin** [comment]
Closing this issue as we have an e2e prototype working. All the open points I took over to Phase 2: https://github.com/elastic/fleet-server/issues/91
