### ISSUE TITLE
[Meta] Fleet Server Phase 2

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#91]
Goal of this phase is to bring Fleet-Server to beta stage. This is a meta tracking issue.

* [x] Use Elasticsearch system indices (@scunningham)
  * [x] Elasticsearch change: https://github.com/elastic/elasticsearch/pull/68919
  * [x] Fleet server system indices https://github.com/elastic/fleet-server/issues/135 (Jay)
  * [x] Switch fleet-server over to system indices
* [x] Elastic Agent with Fleet Server enrolls itself https://github.com/elastic/fleet-server/issues/55
* [x] User permission definition https://github.com/elastic/fleet-server/issues/60 (@scunningham  )
* [x] Support TLS https://github.com/elastic/fleet-server/issues/90 (@blakerouse )
* [x] Metrics of Fleet Server https://github.com/elastic/fleet-server/issues/99 (@scunningham )
* [x] Handle existing actions like upgrade properly ( @blakerouse  )
* [x] Pull out saved object code ( @aleksmaus )
* [x] More granular permissions elastic/fleet-server#101 (@aleksmaus )
* [x] Implement support for API Key metadata. ES reference: https://github.com/elastic/elasticsearch/issues/48182  https://github.com/elastic/fleet-server/issues/193 (@aleksmaus )
* [x] Add support for service tokens for fleet-server (@blakerouse )
* [x] Validate Elasticsearch version for compatibility https://github.com/elastic/fleet-server/issues/167 (@blakerouse )
* [x] Validate fleet-server compatibility in Elastic Agent https://github.com/elastic/beats/issues/24720 (@blakerouse )

Bugs
* [x] .fleet-actions index not found https://github.com/elastic/fleet-server/issues/246

CI

* [x] End to end tests exists for Elastic Agent startup, agent enrollment and receiving policy. https://github.com/elastic/e2e-testing/issues/438 (@blakerouse )
* [ ] Scale testing setup https://github.com/elastic/fleet-server/issues/95 (@aleksmaus )
  * [ ] Basic APM Server testing in Cloud container (@simitt)
  * [ ] Basic fleet-server testing in Cloud container (@scunningham ) 

Docs (@ph )

**Comment by ruflin** [comment]
I checked off e2e tests as some initial work for https://github.com/elastic/e2e-testing/issues/438 was merged. More is needed but tracked in https://github.com/elastic/e2e-testing/issues/438

**Comment by ruflin** [comment]
Closing this issue as all related tasks have been completed. The testing is ongoing and will continue.
